#!/usr/bin/env bash
# Check if an IP address is provided as an argument
# Perform the ping and display the results

ip_address=$1
if [[ $ip_address =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]
then
	ping -c 5 "$ip_address"
else
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
