#!/usr/bin/env bash
# Script to debug and fix Nginx not listening on port 80
sudo rm /etc/nginx/sites-enabled/default
sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/sites-available/default
sudo service nginx restart
