#!/usr/bin/env bash
# Bash script:
# 	Creates the file /var/run/myscript.pid containing its PID
#	Displays To infinity and beyond indefinitely
#	Displays I hate the kill command when receiving a SIGTERM signa
#	Displays Y U no love me?! when receiving a SIGINT signa
#	Deletes the fil


