#!/usr/bin/env bash
# This script displays different messages based on loop iteration.
#	"bad luck" in the 4th
#	"good luck" in the 8th
#	"Best school" in the others

count=1
while [ $count -le 10 ]
do
	if [ $count -eq 4 ]
	then
		echo "bad luck"
	elif [ $count -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((count++))
done
