#!/usr/bin/env bash
# Install the ufw firewall and setup a few rules on web-01.

sudo apt update
sudo apt install ufw
sudo sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
sudo ufw disable
sudo ufw default deny incoming
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo ufw enable
