#!/usr/bin/env bash
# Create a new hosts file with the desired configurations.
# Replace the original hosts file with the new one.

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
