#!/usr/bin/env bash
# Make the fix  short and sweet
pkill apache2
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
service nginx start
